site_name: Auto Home Stack

site_url: 'https://alexkratzer.github.io/autohomestack/'

site_author: 'alexander kratzer'

nav:
    - Home:
        - Auto Home Stack:      index.md
        - Requirements:         'home/requirements.md'
        - Components:           'home/components.md'
    - Control level:        
        - Node RED:             'level_control/node_red.md'
        - control_system:       'level_control/control_system.md'
        - dotNet tool:          'level_control/dotNet_tool.md'
        - Raspberry setup:      'level_control/raspberry_setup.md'
    - Process level:
        - Simatic PLC:          'level_process/simatic_plc.md'
        - PLC program:          'level_process/plc_program.md'
        - Data logger:          'level_process/dataLoggerServer.md'
    - Field level:          
        - IoT Multisensor:      level_field/iot_multisensor.md
        - devices:              level_field/field_level.md
    - Multiroom:
        - multiroom:            multiroom/my_multiroom.md
    - Configuration:
        - master data:          'mds/mds.md'               
        - node topics:          'mds/topics_node.md'
        - plc tag eg:           'mds/plcVarToDB_eg.md'
        - plc tag og:           'mds/plcVarToDB_og.md'
        - plc tag car:          'mds/plcVarToDB_car.md'
        - Patch-Panel:          'mds/patch-panel.md'
        - switch_cabinet:       'mds/switch_cabinet.md'
        - heating circuit:      'mds/heating_circuit_distributor.md'
        - plc lib:              'mds/plc_lib_interface.md'        
    - About:
        - Imprint:              'about/imprint.md'
        - References:           'about/references.md'
        - Plantuml code:        'images/readme_plantuml.md'
        - My wiki:              'about/wiki.md'


# theme: readthedocs
# theme: 'windmill-dark'
# theme: windmill
# extra_css: [extra.css]
theme:
    font:
        text: 'Ubuntu'
        code: 'Ubuntu Mono'
    name: 'material'
    palette:
        primary: 'indigo'
        accent: 'indigo'
#      primary: 'white'
#      accent: 'teal'
    language: 'en'
    favicon: 'images/favicon.ico'
    feature:
      tabs: true
    logo: 'images/house-blue-logo.png'
      #icon: 'settings_power'

markdown_extensions:
    - toc:
        permalink: true
    - admonition
    - codehilite
#    - plantuml-markdown:
#        server: https://localhost:8080
#        # server: https://plantuml.com/plantuml
#        cachedir: /tmp                            # set a non-empty value to enable caching
#        format: png                               # default diagram image format
#        classes: class1,class2                    # default diagram classes
#        title: UML diagram                        # default title (tooltip) for diagram images
#        alt: UML diagram image                    # default `alt` attribute for diagram images
#        priority: 30                              # plugin priority; the higher, the sooner will be applied (default 30)