site_name: Auto Home Stack
repo_url: https://github.com/alexkratzer/autohomestack
site_url: 'https://alexkratzer.github.io/autohomestack/'

site_author: 'alexander kratzer'

nav:
    - Home:                 index.md
    - test:
        test1:
            test1:  test_test
            test2:  test_test
        test2: nochmal
        test3:
            blie
            bla
    - control:              'control_system.md'
    - process:              processing_level.md
    - field level:          field_level.md
    - interface:
        - node topics:          topics_node.md
        - plc lib:              plc_lib_interface.md
        - multiroom:            my_multiroom.md
    
    - About:
        - References:           'references.md'
        - Hints:                hints.md
        - Plantuml code:        images/readme_plantuml.md

# theme: readthedocs
# theme: 'windmill-dark'
# theme: windmill
# extra_css: [extra.css]

markdown_extensions:
    - toc:
        permalink: true
    - admonition
    - codehilite
#    - plantuml-markdown:
#        server: https://localhost:8080
#        # server: https://plantuml.com/plantuml
#        cachedir: /tmp                            # set a non-empty value to enable caching
#        format: png                               # default diagram image format
#        classes: class1,class2                    # default diagram classes
#        title: UML diagram                        # default title (tooltip) for diagram images
#        alt: UML diagram image                    # default `alt` attribute for diagram images
#        priority: 30                              # plugin priority; the higher, the sooner will be applied (default 30)